version: 0.0
os: linux

files:
  - source: ./webapplication/target/demo-0.0.1-SNAPSHOT.war
    destination: /opt/tomcat/webapps

hooks:
  AfterInstall:
   - location: ./infrastructure/aws/codedeploy/afterInstall.sh
     timeout: 180
     runas: centos
  ApplicationStart:
   - location: ./infrastructure/aws/codedeploy/applicationStart.sh
     timeout: 300
     runas: centos
  #ValidateService:
   #- location: ./validateService.sh
    # timeout: 180
#runas: centos
